from src.session.conversation import Conversation

from src.display.display_behavior import display_grandpy_status_code_to_home
from src.display.counting_behavior import user_incivility_count
from src.display.counting_behavior import user_indecency_count
from src.display.counting_behavior import user_incomprehension_count
from src.display.counting_behavior import user_question_answer_count
from src.display.display_behavior import display_grandpy_status_code_to_response
from src.display.display_behavior import display_grandpy_status_code_to_benevolent
from src.display.display_behavior import display_grandpy_status_code_to_mannerless
from src.display.display_behavior import display_grandpy_status_code_to_disrespectful
from src.display.display_behavior import display_grandpy_status_code_to_inconsistency
from src.display import display_behavior